# Generated by Django 3.1.2 on 2020-10-20 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('experience', models.TextField()),
                ('image', models.ImageField(default=None, upload_to='')),
                ('github', models.URLField()),
                ('linkedin', models.URLField()),
                ('degree', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=400)),
                ('university', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=200)),
                ('website', models.URLField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sub_discription', models.CharField(max_length=30)),
                ('discription', models.TextField()),
                ('language', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=200)),
                ('github', models.URLField()),
                ('website', models.URLField(default=None)),
                ('Resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
    ]
