# Generated by Django 3.1.2 on 2020-10-21 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20201021_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.resume'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
