# Generated by Django 3.1.2 on 2020-10-21 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20201021_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.resume'),
        ),
    ]
