# Generated by Django 3.1.2 on 2020-10-21 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20201021_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='name',
            new_name='Name',
        ),
    ]
