# Generated by Django 3.1.2 on 2020-10-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20201021_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='Name',
            new_name='name',
        ),
    ]
